# Generated by Django 2.1.4 on 2018-12-11 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_number", models.IntegerField()),
                ("description", models.TextField()),
                ("list_order", models.IntegerField()),
                (
                    "machine",
                    models.CharField(
                        choices=[
                            ("SMSV", "Small Starvision"),
                            ("PIN1", "Pinnacle 1"),
                            ("PIN2", "Pinnacle 2"),
                            ("MBSV", "Mid Bay Big Starvision"),
                        ],
                        default="PIN1",
                        max_length=4,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="list.Customer"
                    ),
                ),
            ],
        ),
    ]
