# Generated by Django 2.1.4 on 2018-12-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0002_auto_20181211_1756"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="list_order",),
    ]
