# Generated by Django 2.1.4 on 2018-12-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0003_remove_job_list_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job", name="description", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="job", name="job_number", field=models.PositiveIntegerField(),
        ),
    ]
