# Generated by Django 2.1.4 on 2018-12-18 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20181214_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Machine'),
        ),
    ]
