# Generated by Django 2.1.4 on 2019-01-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0007_auto_20181218_0120"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="add_tools",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
