# Generated by Django 2.1.4 on 2019-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0008_job_add_tools"),
    ]

    operations = [
        migrations.AlterModelOptions(name="customer", options={"ordering": ("name",)},),
        migrations.AddField(
            model_name="customer",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
