# Generated by Django 2.1.4 on 2019-01-15 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20190111_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
