# Generated by Django 2.1.4 on 2019-01-15 01:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0010_auto_20190114_2021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="date_added",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
