# Generated by Django 2.1.5 on 2019-02-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('list', '0012_job_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_completed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
