# Generated by Django 2.2.3 on 2019-08-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0016_auto_20190515_1312"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="setup_sheets",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("-", "N/A")],
                default="N",
                max_length=1,
            ),
        ),
    ]
