# Generated by Django 2.2.3 on 2019-12-09 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0018_auto_20190802_0922"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ltd_item_number", models.IntegerField()),
                ("outsource_detail_number", models.CharField(max_length=24)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="list.Job"
                    ),
                ),
            ],
        ),
    ]
